fun main(args: Array<String>) {
    val root = Node(6)
    val tree = Tree(root)
    tree.add(5)
    tree.add(7)
    tree.add(10)
    tree.add(14)
    tree.delete(10)
    println(tree.getSize())
    println(tree.dfSearch(14))
    println(tree.dfSearch(141))
    println(tree.getLeavesCount())
    println(tree.isBalanced())
    tree.bfTraversal()
}