fun main(args: Array<String>) {
    val root = Node(6)
    val tree = Tree(root)
    tree.add(5)
    tree.add(7)
    tree.add(10)
    tree.add(14)
//    tree.add(9)
//    tree.add(12)
//    tree.add(42)
//    tree.add(11)
    println(tree.getSize())
    println(tree.getLeavesCount())
    println(tree.printTree())
    println(tree.isBalanced())
}